In [ ]:
import numpy as np # Traer al espacio de trabajo la libreria NumPy

In [ ]:
arr = [7, 2, 9, 10]

In [ ]:
type(arr)

list

In [ ]:
arr_np = np.array(arr)
arr_np

array([ 7,  2,  9, 10])

In [ ]:
type(arr_np)

numpy.ndarray

In [ ]:
result = arr_np * arr_np
result

array([ 49,   4,  81, 100])

In [ ]:
matrix = arr_np * np.transpose(arr_np)
matrix

array([ 49,   4,  81, 100])

In [ ]:
mat = [[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]
mat

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15]]

In [ ]:
mat2D = np.array(mat)
mat2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
arr_np.shape

(4,)

In [ ]:
mat2D.shape

(3, 5)

In [ ]:
arr_3d = [[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],[[13,14,15],[16,17,18]]]
mat3D = np.array(arr_3d)
mat3D.shape

(3, 2, 3)

In [ ]:
mat3D[1,1,0] = "Lazaro"
mat3D

ValueError: ignored

In [ ]:
mat2D

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [ ]:
mat2D[1, 4] = 2023
mat2D

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9, 2023],
       [  11,   12,   13,   14,   15]])

In [ ]:
mat2D[::2, ::3]

array([[ 1,  4],
       [11, 14]])

In [ ]:
mat2D

array([[   1,    2,    3,    4,    5],
       [   6,    7,    8,    9, 2023],
       [  11,   12,   13,   14,   15]])

In [ ]:
mat2D[:,1]

array([ 2,  7, 12])

In [ ]:
temp0 = np.zeros((3,12),dtype=int)
temp0

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
temp1 = np.ones((3,12),dtype=int)
temp1

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
temp_rnd = np.random.randn(3,12)
temp_rnd

array([[ 1.39049612, -0.23750525, -0.58059192, -0.19388154,  0.19969931,
         1.69937616, -0.01006373,  0.12189795, -1.55994728,  1.80098071,
         1.42002283, -1.57574296],
       [ 0.60377619, -0.29763683,  1.035932  ,  0.13861576, -0.29124565,
         1.73209886, -2.1007887 , -1.88095899, -0.07422885,  1.22150787,
        -1.39060069, -0.53612291],
       [-1.16098848,  0.59402983,  1.2089544 ,  0.88340885,  0.48492446,
         1.28616617,  1.28638621,  0.26653726,  0.06416325,  0.44125063,
        -1.39862979, -0.10889336]])

In [ ]:
temp23 = temp0
temp23.fill(2023)
temp23

array([[2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
        2023],
       [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
        2023],
       [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
        2023]])

In [ ]:
temp0

array([[2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
        2023],
       [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
        2023],
       [2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023, 2023,
        2023]])

In [ ]:
temp0.fill(0)
temp0

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
temp23

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
temp23 = np.copy(temp0)
temp23

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
temp23.fill(1942)
temp23

array([[1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942,
        1942],
       [1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942,
        1942],
       [1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942, 1942,
        1942]])

In [ ]:
temp0

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
arr = mat2D.tolist()
arr

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 2023], [11, 12, 13, 14, 15]]

In [ ]:
edades = np.array([19,20,19,19,20,21,20,19,21,20,19])
edades

array([19, 20, 19, 19, 20, 21, 20, 19, 21, 20, 19])

In [ ]:
np.histogram(edades, bins=[19, 20, 21])

(array([5, 6]), array([19, 20, 21]))

In [ ]:
arr_np = [1, 3, 67, 2, 0 ,23, 3,0,1,0,5,3,6,8,0,56,9,0,56,0]

In [ ]:
arr_np

[1, 3, 67, 2, 0, 23, 3, 0, 1, 0, 5, 3, 6, 8, 0, 56, 9, 0, 56, 0]

In [ ]:
np.where(arr_np == 0)

(array([], dtype=int64),)

In [ ]:
res = [arr_np < 5]

TypeError: ignored

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series(['Matemáticas', 6, 'Economía', True, 'Inglés'])
s

0    Matemáticas
1              6
2       Economía
3           True
4         Inglés
dtype: object

In [ ]:
p = s[1] + 7
p

13

In [ ]:
l =  not s[3]
l

False

In [ ]:
o = s[0]+ 7

TypeError: ignored

In [ ]:
s = pd.Series({'Matemáticas': 6.0, 'Economía': 4.5, 'Programación': 8.5})
s

Matemáticas     6.0
Economía        4.5
Programación    8.5
dtype: float64

In [ ]:
s["Programación"]

8.5

In [ ]:
s[2]

8.5

In [ ]:
s.dtype

dtype('float64')

In [ ]:
s.size

3

In [ ]:
s.index

Index(['Matemáticas', 'Economía', 'Programación'], dtype='object')

In [ ]:
s[1:]

Economía        4.5
Programación    8.5
dtype: float64

In [ ]:
s["Economía":]

Economía        4.5
Programación    8.5
dtype: float64

In [ ]:
s.sum()

19.0

In [ ]:
s.max()

8.5

In [ ]:
s.describe()

count    3.000000
mean     6.333333
std      2.020726
min      4.500000
25%      5.250000
50%      6.000000
75%      7.250000
max      8.500000
dtype: float64

In [ ]:
s = s / 100
s = ((s ** 2) / (s + s)) * 1000
s

Matemáticas     0.7500
Economía        0.5625
Programación    1.0625
dtype: float64

In [ ]:
s >= 7.0

Matemáticas     False
Economía        False
Programación     True
dtype: bool

In [ ]:
s[(s >= 8) & (s < 10) & (s != 8.5)]

Series([], dtype: float64)

In [ ]:
import numpy as np

In [ ]:
s = pd.Series([1, 2, None, 4, np.NaN, 6])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
5    6.0
dtype: float64

In [ ]:
s.describe()

count    4.000000
mean     3.250000
std      2.217356
min      1.000000
25%      1.750000
50%      3.000000
75%      4.500000
max      6.000000
dtype: float64

In [ ]:
s1 = s.dropna()
s1

0    1.0
1    2.0
3    4.0
5    6.0
dtype: float64

In [ ]:
datos = {'nombre':['María', 'Luis', 'Carmen', 'Antonio'], 'edad':[18, 22, 20, 21], 'grado':['Economía', 'Medicina', 'Arquitectura', 'Economía'], 'correo':['maria@gmail.com', 'luis@yahoo.es', 'carmen@gmail.com', 'antonio@gmail.com'] }
datos

{'nombre': ['María', 'Luis', 'Carmen', 'Antonio'],
 'edad': [18, 22, 20, 21],
 'grado': ['Economía', 'Medicina', 'Arquitectura', 'Economía'],
 'correo': ['maria@gmail.com',
  'luis@yahoo.es',
  'carmen@gmail.com',
  'antonio@gmail.com']}

In [ ]:
df = pd.DataFrame(datos)
df

nombre  edad         grado             correo
0    María    18      Economía    maria@gmail.com
1     Luis    22      Medicina      luis@yahoo.es
2   Carmen    20  Arquitectura   carmen@gmail.com
3  Antonio    21      Economía  antonio@gmail.com

In [ ]:
col_names = ["nombre", "edad", "grado", "correo"]
row_names = [0,1,2,3]
nombre = ["Maria","Luis","Carmen","Antonio"]
edad = [18, 22, 20, 21]
grado = ["economia","medicina","arq","economia"]
correo = ["1@1.com", "2@2.com", "3@3.com", "4@4.com"]

df_1 = pd.DataFrame(np.transpose([nombre,edad,grado,correo]),columns=col_names,index=row_names)
df_1

nombre edad     grado   correo
0    Maria   18  economia  1@1.com
1     Luis   22  medicina  2@2.com
2   Carmen   20       arq  3@3.com
3  Antonio   21  economia  4@4.com

In [ ]:
val = np.random.randn(5,12)
df_2 = pd.DataFrame(val)
df_2

0         1         2         3         4         5         6   \
0  0.560010 -0.174876 -1.235307 -0.897206 -0.637617  1.043809  1.064718   
1 -2.008873  0.418066  0.911748 -0.925310 -1.093258  0.724471 -0.672545   
2 -1.004003  0.117864 -1.158435 -0.460907 -0.621654 -1.444988  1.597828   
3  0.084306 -0.927347  1.021406  0.590922  0.959731 -0.049683  0.082792   
4  0.823131  0.529099  2.387175  1.541391  1.064137 -0.185185  0.700419   

         7         8         9         10        11  
0 -0.940620 -1.200233  1.925443  0.217453 -2.022971  
1 -0.783584  1.264716  1.492135 -0.755308  1.863121  
2  0.354204  0.855532 -0.488978 -1.065884 -0.966412  
3 -0.537644  0.853055  1.026770  0.798554  0.868918  
4 -0.074208 -0.598223 -0.593800  0.607708 -0.164082

In [ ]:
colesterol = df = pd.read_csv( 'https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesteroles.csv', sep=';', decimal=',')
colesterol

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
colesterol.to_csv("F:\lbustio\OneDrive\OneDrive - Universidad Iberoamericana, A.C\Escritorio\Diplomado\Sesión 1\test.csv",sep="*")

In [ ]:
colesterol.shape

(14, 6)

In [ ]:
df = colesterol

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   nombre      14 non-null     object 
 1   edad        14 non-null     int64  
 2   sexo        14 non-null     object 
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
dtypes: float64(3), int64(1), object(2)
memory usage: 800.0+ bytes


In [ ]:
df.size

84

In [ ]:
df.dtypes

nombre         object
edad            int64
sexo           object
peso          float64
altura        float64
colesterol    float64
dtype: object

In [ ]:
df.head(3)

nombre  edad sexo  peso  altura  colesterol
0  José Luis Martínez Izquierdo    18    H  85.0    1.79       182.0
1                Rosa Díaz Díaz    32    M  65.0    1.73       232.0
2         Javier García Sánchez    24    H   NaN    1.81       191.0

In [ ]:
df.tail(3)

nombre  edad sexo   peso  altura  colesterol
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
newcolnames = {"nombre" : "name",	"edad" : "age", "sexo" : "sex", "peso" : "weight", "altura" : "height", "colesterol" : "colesterol"}
newcolnames

{'nombre': 'name',
 'edad': 'age',
 'sexo': 'sex',
 'peso': 'weight',
 'altura': 'height',
 'colesterol': 'colesterol'}

In [ ]:
df1 = df.rename(columns=newcolnames)
df1

name  age sex  weight  height  colesterol
0      José Luis Martínez Izquierdo   18   H    85.0    1.79       182.0
1                    Rosa Díaz Díaz   32   M    65.0    1.73       232.0
2             Javier García Sánchez   24   H     NaN    1.81       191.0
3               Carmen López Pinzón   35   M    65.0    1.70       200.0
4              Marisa López Collado   46   M    51.0    1.58       148.0
5                 Antonio Ruiz Cruz   68   H    66.0    1.74       249.0
6           Antonio Fernández Ocaña   51   H    62.0    1.72       276.0
7             Pilar Martín González   22   M    60.0    1.66         NaN
8              Pedro Gálvez Tenorio   35   H    90.0    1.94       241.0
9           Santiago Reillo Manzano   46   H    75.0    1.85       280.0
10            Macarena Álvarez Luna   53   M    55.0    1.62       262.0
11       José María de la Guía Sanz   58   H    78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez   27   H   109.0    1.98       210.0
13            Carolina Rubio Moreno   20   M    61.0    1.77       194.0

In [ ]:
df.loc[(1,5,7),("edad", "sexo")]

edad sexo
1    32    M
5    68    H
7    22    M

In [ ]:
df.iloc[3:,4::2]


altura
3     1.70
4     1.58
5     1.74
6     1.72
7     1.66
8     1.94
9     1.85
10    1.62
11    1.87
12    1.98
13    1.77

In [ ]:
df

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
diabetes = pd.Series([True,False,True,True,False,False],dtype=bool)
diabetes

0     True
1    False
2     True
3     True
4    False
5    False
dtype: bool

In [ ]:
df["diabetes"] = diabetes
df

nombre  edad sexo   peso  altura  colesterol  \
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0   
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0   
2             Javier García Sánchez    24    H    NaN    1.81       191.0   
3               Carmen López Pinzón    35    M   65.0    1.70       200.0   
4              Marisa López Collado    46    M   51.0    1.58       148.0   
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0   
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0   
7             Pilar Martín González    22    M   60.0    1.66         NaN   
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0   
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0   
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0   
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0   
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0   
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0   

   diabetes  
0      True  
1     False  
2      True  
3      True  
4     False  
5     False  
6       NaN  
7       NaN  
8       NaN  
9       NaN  
10      NaN  
11      NaN  
12      NaN  
13      NaN

In [ ]:
df.isnull().sum()

nombre        0
edad          0
sexo          0
peso          1
altura        0
colesterol    1
diabetes      8
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   nombre      14 non-null     object 
 1   edad        14 non-null     int64  
 2   sexo        14 non-null     object 
 3   peso        13 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
 6   diabetes    6 non-null      object 
dtypes: float64(3), int64(1), object(3)
memory usage: 912.0+ bytes


In [ ]:
df.describe()

edad        peso     altura  colesterol
count  14.000000   13.000000  14.000000   13.000000
mean   38.214286   70.923077   1.768571  220.230769
std    15.621379   16.126901   0.115016   39.847948
min    18.000000   51.000000   1.580000  148.000000
25%    24.750000   61.000000   1.705000  194.000000
50%    35.000000   65.000000   1.755000  210.000000
75%    49.750000   78.000000   1.840000  249.000000
max    68.000000  109.000000   1.980000  280.000000

In [ ]:
df["peso"].fillna(np.mean([69.66, 79.77]), inplace=True)
df

nombre  edad sexo     peso  altura  colesterol  \
0      José Luis Martínez Izquierdo    18    H   85.000    1.79       182.0   
1                    Rosa Díaz Díaz    32    M   65.000    1.73       232.0   
2             Javier García Sánchez    24    H   74.715    1.81       191.0   
3               Carmen López Pinzón    35    M   65.000    1.70       200.0   
4              Marisa López Collado    46    M   51.000    1.58       148.0   
5                 Antonio Ruiz Cruz    68    H   66.000    1.74       249.0   
6           Antonio Fernández Ocaña    51    H   62.000    1.72       276.0   
7             Pilar Martín González    22    M   60.000    1.66         NaN   
8              Pedro Gálvez Tenorio    35    H   90.000    1.94       241.0   
9           Santiago Reillo Manzano    46    H   75.000    1.85       280.0   
10            Macarena Álvarez Luna    53    M   55.000    1.62       262.0   
11       José María de la Guía Sanz    58    H   78.000    1.87       198.0   
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.000    1.98       210.0   
13            Carolina Rubio Moreno    20    M   61.000    1.77       194.0   

   diabetes  
0      True  
1     False  
2      True  
3      True  
4     False  
5     False  
6       NaN  
7       NaN  
8       NaN  
9       NaN  
10      NaN  
11      NaN  
12      NaN  
13      NaN

In [ ]:
df.isna().sum()

nombre        0
edad          0
sexo          0
peso          0
altura        0
colesterol    1
diabetes      8
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   nombre      14 non-null     object 
 1   edad        14 non-null     int64  
 2   sexo        14 non-null     object 
 3   peso        14 non-null     float64
 4   altura      14 non-null     float64
 5   colesterol  13 non-null     float64
 6   diabetes    6 non-null      object 
dtypes: float64(3), int64(1), object(3)
memory usage: 912.0+ bytes


In [ ]:
df.loc[(df["peso"] >= 70) & (df["peso"] <= 75) & (df["altura"] > 1.7) & (df["colesterol"] >= 200), "colesterol"]=True

In [ ]:
df

nombre  edad sexo   peso  altura colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79      182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73      232.0
2             Javier García Sánchez    24    H    NaN    1.81      191.0
3               Carmen López Pinzón    35    M   65.0    1.70      200.0
4              Marisa López Collado    46    M   51.0    1.58      148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74      249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72      276.0
7             Pilar Martín González    22    M   60.0    1.66        NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94      241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       True
10            Macarena Álvarez Luna    53    M   55.0    1.62      262.0
11       José María de la Guía Sanz    58    H   78.0    1.87      198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98      210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77      194.0

In [ ]:
df

nombre  edad sexo   peso  altura colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79      182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73      232.0
2             Javier García Sánchez    24    H    NaN    1.81      191.0
3               Carmen López Pinzón    35    M   65.0    1.70      200.0
4              Marisa López Collado    46    M   51.0    1.58      148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74      249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72      276.0
7             Pilar Martín González    22    M   60.0    1.66        NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94      241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       True
10            Macarena Álvarez Luna    53    M   55.0    1.62      262.0
11       José María de la Guía Sanz    58    H   78.0    1.87      198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98      210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77      194.0

In [ ]:
df["altura"] = df["altura"]*100
df

nombre  edad sexo   peso  altura colesterol
0      José Luis Martínez Izquierdo    18    H   85.0   179.0      182.0
1                    Rosa Díaz Díaz    32    M   65.0   173.0      232.0
2             Javier García Sánchez    24    H    NaN   181.0      191.0
3               Carmen López Pinzón    35    M   65.0   170.0      200.0
4              Marisa López Collado    46    M   51.0   158.0      148.0
5                 Antonio Ruiz Cruz    68    H   66.0   174.0      249.0
6           Antonio Fernández Ocaña    51    H   62.0   172.0      276.0
7             Pilar Martín González    22    M   60.0   166.0        NaN
8              Pedro Gálvez Tenorio    35    H   90.0   194.0      241.0
9           Santiago Reillo Manzano    46    H   75.0   185.0       True
10            Macarena Álvarez Luna    53    M   55.0   162.0      262.0
11       José María de la Guía Sanz    58    H   78.0   187.0      198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0      210.0
13            Carolina Rubio Moreno    20    M   61.0   177.0      194.0

In [ ]:
df["sexo" == 'M']

KeyError: ignored

In [ ]:
df

nombre  edad sexo   peso  altura colesterol
0      José Luis Martínez Izquierdo    18    H   85.0   179.0      182.0
1                    Rosa Díaz Díaz    32    M   65.0   173.0      232.0
2             Javier García Sánchez    24    H    NaN   181.0      191.0
3               Carmen López Pinzón    35    M   65.0   170.0      200.0
4              Marisa López Collado    46    M   51.0   158.0      148.0
5                 Antonio Ruiz Cruz    68    H   66.0   174.0      249.0
6           Antonio Fernández Ocaña    51    H   62.0   172.0      276.0
7             Pilar Martín González    22    M   60.0   166.0        NaN
8              Pedro Gálvez Tenorio    35    H   90.0   194.0      241.0
9           Santiago Reillo Manzano    46    H   75.0   185.0       True
10            Macarena Álvarez Luna    53    M   55.0   162.0      262.0
11       José María de la Guía Sanz    58    H   78.0   187.0      198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0      210.0
13            Carolina Rubio Moreno    20    M   61.0   177.0      194.0

In [ ]:
colesterol = df.pop("colesterol")
df

nombre  edad sexo   peso  altura
0      José Luis Martínez Izquierdo    18    H   85.0   179.0
1                    Rosa Díaz Díaz    32    M   65.0   173.0
2             Javier García Sánchez    24    H    NaN   181.0
3               Carmen López Pinzón    35    M   65.0   170.0
4              Marisa López Collado    46    M   51.0   158.0
5                 Antonio Ruiz Cruz    68    H   66.0   174.0
6           Antonio Fernández Ocaña    51    H   62.0   172.0
7             Pilar Martín González    22    M   60.0   166.0
8              Pedro Gálvez Tenorio    35    H   90.0   194.0
9           Santiago Reillo Manzano    46    H   75.0   185.0
10            Macarena Álvarez Luna    53    M   55.0   162.0
11       José María de la Guía Sanz    58    H   78.0   187.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0
13            Carolina Rubio Moreno    20    M   61.0   177.0

In [ ]:
colesterol

0     182.0
1     232.0
2     191.0
3     200.0
4     148.0
5     249.0
6     276.0
7       NaN
8     241.0
9      True
10    262.0
11    198.0
12    210.0
13    194.0
Name: colesterol, dtype: object

In [ ]:
df["colesterol"] = colesterol

In [ ]:
df

nombre  edad sexo   peso  altura colesterol
0      José Luis Martínez Izquierdo    18    H   85.0   179.0      182.0
1                    Rosa Díaz Díaz    32    M   65.0   173.0      232.0
2             Javier García Sánchez    24    H    NaN   181.0      191.0
3               Carmen López Pinzón    35    M   65.0   170.0      200.0
4              Marisa López Collado    46    M   51.0   158.0      148.0
5                 Antonio Ruiz Cruz    68    H   66.0   174.0      249.0
6           Antonio Fernández Ocaña    51    H   62.0   172.0      276.0
7             Pilar Martín González    22    M   60.0   166.0        NaN
8              Pedro Gálvez Tenorio    35    H   90.0   194.0      241.0
9           Santiago Reillo Manzano    46    H   75.0   185.0       True
10            Macarena Álvarez Luna    53    M   55.0   162.0      262.0
11       José María de la Guía Sanz    58    H   78.0   187.0      198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0      210.0
13            Carolina Rubio Moreno    20    M   61.0   177.0      194.0

In [ ]:
colesterol

NameError: ignored

In [ ]:
salida = df.pop(("colesterol", "peso"))

In [ ]:
df = pd.read_csv( 'https://raw.githubusercontent.com/asalber/manual-python/master/datos/colesterol.csv')

In [ ]:
df

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df = df.append(pd.Series(['Carlos Rivas', 28, 'H', 89.0, 1.78, 245.0], index=['nombre','edad','sexo','peso','altura','colesterol']), ignore_index=True)

In [ ]:
df

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0
14                     Carlos Rivas    28    H   89.0    1.78       245.0
15                     Carlos Rivas    28    H   89.0    1.78       245.0

In [ ]:
df1 = df.drop([1,3])
df1

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
2             Javier García Sánchez    24    H    NaN    1.81       191.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
7             Pilar Martín González    22    M   60.0    1.66         NaN
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df.dropna(inplace=True)
df

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0    1.79       182.0
1                    Rosa Díaz Díaz    32    M   65.0    1.73       232.0
3               Carmen López Pinzón    35    M   65.0    1.70       200.0
4              Marisa López Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernández Ocaña    51    H   62.0    1.72       276.0
8              Pedro Gálvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Álvarez Luna    53    M   55.0    1.62       262.0
11       José María de la Guía Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0

In [ ]:
df["altura"] = df["altura"]*100
df

nombre  edad sexo   peso  altura  colesterol
0      José Luis Martínez Izquierdo    18    H   85.0   179.0       182.0
1                    Rosa Díaz Díaz    32    M   65.0   173.0       232.0
2             Javier García Sánchez    24    H    NaN   181.0       191.0
3               Carmen López Pinzón    35    M   65.0   170.0       200.0
4              Marisa López Collado    46    M   51.0   158.0       148.0
5                 Antonio Ruiz Cruz    68    H   66.0   174.0       249.0
6           Antonio Fernández Ocaña    51    H   62.0   172.0       276.0
7             Pilar Martín González    22    M   60.0   166.0         NaN
8              Pedro Gálvez Tenorio    35    H   90.0   194.0       241.0
9           Santiago Reillo Manzano    46    H   75.0   185.0       280.0
10            Macarena Álvarez Luna    53    M   55.0   162.0       262.0
11       José María de la Guía Sanz    58    H   78.0   187.0       198.0
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0       210.0
13            Carolina Rubio Moreno    20    M   61.0   177.0       194.0
14                     Carlos Rivas    28    H   89.0   178.0       245.0

In [ ]:
df.groupby("sexo").groups

{'H': [0, 2, 5, 6, 8, 9, 11, 12, 14], 'M': [1, 3, 4, 7, 10, 13]}

In [ ]:
df["talla"] = "Chico"
df

nombre  edad sexo   peso  altura  colesterol  \
0      José Luis Martínez Izquierdo    18    H   85.0   179.0       182.0   
1                    Rosa Díaz Díaz    32    M   65.0   173.0       232.0   
2             Javier García Sánchez    24    H    NaN   181.0       191.0   
3               Carmen López Pinzón    35    M   65.0   170.0       200.0   
4              Marisa López Collado    46    M   51.0   158.0       148.0   
5                 Antonio Ruiz Cruz    68    H   66.0   174.0       249.0   
6           Antonio Fernández Ocaña    51    H   62.0   172.0       276.0   
7             Pilar Martín González    22    M   60.0   166.0         NaN   
8              Pedro Gálvez Tenorio    35    H   90.0   194.0       241.0   
9           Santiago Reillo Manzano    46    H   75.0   185.0       280.0   
10            Macarena Álvarez Luna    53    M   55.0   162.0       262.0   
11       José María de la Guía Sanz    58    H   78.0   187.0       198.0   
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0       210.0   
13            Carolina Rubio Moreno    20    M   61.0   177.0       194.0   
14                     Carlos Rivas    28    H   89.0   178.0       245.0   

    talla  
0   Chico  
1   Chico  
2   Chico  
3   Chico  
4   Chico  
5   Chico  
6   Chico  
7   Chico  
8   Chico  
9   Chico  
10  Chico  
11  Chico  
12  Chico  
13  Chico  
14  Chico

In [ ]:
df.loc[(df["altura"] > 160) & (df["altura"] <= 175), "talla"] = "Medio"
df

nombre  edad sexo   peso  altura  colesterol  \
0      José Luis Martínez Izquierdo    18    H   85.0   179.0       182.0   
1                    Rosa Díaz Díaz    32    M   65.0   173.0       232.0   
2             Javier García Sánchez    24    H    NaN   181.0       191.0   
3               Carmen López Pinzón    35    M   65.0   170.0       200.0   
4              Marisa López Collado    46    M   51.0   158.0       148.0   
5                 Antonio Ruiz Cruz    68    H   66.0   174.0       249.0   
6           Antonio Fernández Ocaña    51    H   62.0   172.0       276.0   
7             Pilar Martín González    22    M   60.0   166.0         NaN   
8              Pedro Gálvez Tenorio    35    H   90.0   194.0       241.0   
9           Santiago Reillo Manzano    46    H   75.0   185.0       280.0   
10            Macarena Álvarez Luna    53    M   55.0   162.0       262.0   
11       José María de la Guía Sanz    58    H   78.0   187.0       198.0   
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0       210.0   
13            Carolina Rubio Moreno    20    M   61.0   177.0       194.0   
14                     Carlos Rivas    28    H   89.0   178.0       245.0   

    talla  
0   Chico  
1   Medio  
2   Chico  
3   Medio  
4   Chico  
5   Medio  
6   Medio  
7   Medio  
8   Chico  
9   Chico  
10  Medio  
11  Chico  
12  Chico  
13  Chico  
14  Chico

In [ ]:
df.loc[df["altura"] > 175, "talla"] = "Alto"
df

nombre  edad sexo   peso  altura  colesterol  \
0      José Luis Martínez Izquierdo    18    H   85.0   179.0       182.0   
1                    Rosa Díaz Díaz    32    M   65.0   173.0       232.0   
2             Javier García Sánchez    24    H    NaN   181.0       191.0   
3               Carmen López Pinzón    35    M   65.0   170.0       200.0   
4              Marisa López Collado    46    M   51.0   158.0       148.0   
5                 Antonio Ruiz Cruz    68    H   66.0   174.0       249.0   
6           Antonio Fernández Ocaña    51    H   62.0   172.0       276.0   
7             Pilar Martín González    22    M   60.0   166.0         NaN   
8              Pedro Gálvez Tenorio    35    H   90.0   194.0       241.0   
9           Santiago Reillo Manzano    46    H   75.0   185.0       280.0   
10            Macarena Álvarez Luna    53    M   55.0   162.0       262.0   
11       José María de la Guía Sanz    58    H   78.0   187.0       198.0   
12  Miguel Angel Cuadrado Gutiérrez    27    H  109.0   198.0       210.0   
13            Carolina Rubio Moreno    20    M   61.0   177.0       194.0   
14                     Carlos Rivas    28    H   89.0   178.0       245.0   

    talla  
0    Alto  
1   Medio  
2    Alto  
3   Medio  
4   Chico  
5   Medio  
6   Medio  
7   Medio  
8    Alto  
9    Alto  
10  Medio  
11   Alto  
12   Alto  
13   Alto  
14   Alto

In [ ]:
df.groupby(["sexo","talla",]).get_group(("H","Chico"))

KeyError: ignored

In [ ]:
datos = {'nombre':['María', 'Luis', 'Carmen'], 'edad':[18, 22, 20], 'Matemáticas':[8.5, 7, 3.5], 'Economía':[8, 6.5, 5], 'Programación':[6.5, 4, 9]}

In [ ]:
datos

{'nombre': ['María', 'Luis', 'Carmen'],
 'edad': [18, 22, 20],
 'Matemáticas': [8.5, 7, 3.5],
 'Economía': [8, 6.5, 5],
 'Programación': [6.5, 4, 9]}

In [ ]:
eje = pd.DataFrame(datos)
eje

nombre  edad  Matemáticas  Economía  Programación
0   María    18          8.5       8.0           6.5
1    Luis    22          7.0       6.5           4.0
2  Carmen    20          3.5       5.0           9.0

In [ ]:
df1 = eje.melt(id_vars=['nombre', 'edad'], var_name='asignatura', value_name='nota')
df1

nombre  edad    asignatura  nota
0   María    18   Matemáticas   8.5
1    Luis    22   Matemáticas   7.0
2  Carmen    20   Matemáticas   3.5
3   María    18      Economía   8.0
4    Luis    22      Economía   6.5
5  Carmen    20      Economía   5.0
6   María    18  Programación   6.5
7    Luis    22  Programación   4.0
8  Carmen    20  Programación   9.0

In [ ]:
print(df1.pivot(index='nombre', columns='asignatura', values='nota'))

asignatura  Economía  Matemáticas  Programación
nombre                                         
Carmen           5.0          3.5           9.0
Luis             6.5          7.0           4.0
María            8.0          8.5           6.5


In [ ]:
p = 1.236589

print(round(p,2))

1.24


In [ ]:
import io
from google.colab import files

In [ ]:
uploaded = files.upload()

Saving colesteroles.csv to colesteroles.csv


In [ ]:
uploaded

{'colesteroles.csv': b'nombre;edad;sexo;peso;altura;colesterol\r\nJose Luis Martinez Izquierdo;18;H;85;1,79;182\r\nRosa Diaz;32;M;65;1,73;232\r\nJavier  Sanchez;24;H;;1,81;191\r\nCarmen Lopez Pinzon;35;M;65;1,70;200\r\nMarisa Lopez Collado;46;M;51;1,58;148\r\nAntonio Ruiz Cruz;68;H;66;1,74;249\r\nAntonio Fernandez Ocana;51;H;62;1,72;276\r\nPilar Gonzalez;22;M;60;1,66;\r\nPedro Galvez Tenorio;35;H;90;1,94;241\r\nSantiago Reillo Manzano;46;H;75;1,85;280\r\nMacarena Alvarez Luna;53;M;55;1,62;262\r\nJose de la Guardia Sanz;58;H;78;1,87;198\r\nMiguel Angel Cuadrado Gutierrez;27;H;109;1,98;210\r\nCarolina Rubio Moreno;20;M;61;1,77;194\r\n'}

In [ ]:
df = pd.read_csv(io.BytesIO(uploaded["colesteroles.csv"]), sep=";", decimal=",")
df

nombre  edad sexo   peso  altura  colesterol
0      Jose Luis Martinez Izquierdo    18    H   85.0    1.79       182.0
1                         Rosa Diaz    32    M   65.0    1.73       232.0
2                   Javier  Sanchez    24    H    NaN    1.81       191.0
3               Carmen Lopez Pinzon    35    M   65.0    1.70       200.0
4              Marisa Lopez Collado    46    M   51.0    1.58       148.0
5                 Antonio Ruiz Cruz    68    H   66.0    1.74       249.0
6           Antonio Fernandez Ocana    51    H   62.0    1.72       276.0
7                    Pilar Gonzalez    22    M   60.0    1.66         NaN
8              Pedro Galvez Tenorio    35    H   90.0    1.94       241.0
9           Santiago Reillo Manzano    46    H   75.0    1.85       280.0
10            Macarena Alvarez Luna    53    M   55.0    1.62       262.0
11          Jose de la Guardia Sanz    58    H   78.0    1.87       198.0
12  Miguel Angel Cuadrado Gutierrez    27    H  109.0    1.98       210.0
13            Carolina Rubio Moreno    20    M   61.0    1.77       194.0